name: Auto Create Pull Request

on:
  push:
    branches:
      - 'feature-*'  # Triggers only on feature branches

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Git configuration
        run: |
          git config --global user.email "youremail@example.com"
          git config --global user.name "Your Name"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4  # Try using v4
        with:
          token: ${{ secrets.My_token }}
          base: main
          branch: ${{ github.head_ref }}  # Use head_ref to get the branch name
          title: "Auto PR from ${{ github.head_ref }}"
          body: "This PR was automatically created by GitHub Actions."
          draft: false

