name: Auto Create Pull Request

on:
  push:
    branches:
      - 'feature-*'  # Triggers only on feature branches

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3  # Use v3 instead of v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ github.ref_name }}
          title: "Auto PR from ${{ github.ref_name }}"
          body: "This PR was automatically created by GitHub Actions."
          draft: false
