name: Auto Create Pull Request

on:
  push:
    branches:
      - 'feature-*'  # Triggers only on feature branches

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.MUNI_TOKEN }}  # Use your token stored in secrets
          base: main  # The target branch to merge into
          branch: ${{ github.ref_name }}  # The feature branch name
          title: "Auto PR from ${{ github.ref_name }}"
          body: "This PR was automatically created by GitHub Actions."
          draft: false  # Make sure this is false, meaning the PR will be ready to mer:g
